pipeline {
    agent { label 'mac-agent' }

    environment {
        JAR_NAME = "AirlineManagementSystem-0.0.1-SNAPSHOT.jar"
        EC2_HOST = "ec2-user@54.174.2.250"
        PEM_KEY = credentials('ec2-ssh-key')
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t airline-management .'
            }
        }

        stage('Deploy to EC2') {
            steps {
                sh "scp -i ${PEM_KEY} target/${JAR_NAME} ${EC2_HOST}:/home/ec2-user/"
                sh """
                ssh -i ${PEM_KEY} ${EC2_HOST} << EOF
                    pkill -f '${JAR_NAME}' || true
                    nohup java -jar ${JAR_NAME} > app.log 2>&1 &
                EOF
                """
            }
        }
    }
}
